apiVersion: v1
kind: ConfigMap
metadata:
  name: image-pin-config
data:
  default.js: |
    'use strict';
    var config = {
      'rethinkdb': {
        'host': 'rethinkdb-db-access',
        'port': 28015,
        'db': 'image_pin'
      },
      'ports': {
        'http': 80,
      },
      'url': 'image-pin.thejsj.com',
      'googleAnaylitcsUACode': false,
      'github': {
        'clientID': 'a0476c6df3da1996992d',
        'clientSecret': '21b54e1864ea818e66f01663b3412e7dacf20538',
      }
    };
    module.exports = config;
